### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GPU-Solution** [Exlo84/ethopool#2]
First of all, my apologies, this isn't an issue, just needed to contact u to ask.. 
How can i do to sign my mined blocks like this? 
![imagen](https://user-images.githubusercontent.com/86377224/203915125-79281fed-262a-41f8-bf8d-809d82edd4c8.png)
I was testing your pool and it's likely that I'll implement a pool based on your code, and I'd like to be able to identify the blocks I've mined, just like 'coolpool.top' does in the example image.
cheers

**Comment by Exlo84** [comment]
Hi. 
Unfortunately, you cannot self assign your pool on the explorer, but if you contact **Dox#1570** over at Discord( https://discord.gg/MFn9Tmz ) he should be able to do so manually.
